### ISSUE TITLE
How to configure and integrate Zabbix server with ZabbixJ agent

### ISSUE THREAD

**Issue by nasibulloh** [michaelquigley/zabbixj#14]
I want to integrate ZabbixJ agent with Zabbix Server but I don't know how It is done.

**Comment by michaelquigley** [comment]
I would recommend starting with the Zabbix documentation:

https://www.zabbix.com/documentation/3.0/manual

The Zabbix/J agent is a pure-Java implementation of the Zabbix "agent" concept:

https://www.zabbix.com/documentation/3.0/manual/concepts/agent
