### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by AllardKrings** [michaelquigley/zabbixj#16]
Hello,

I am relatively new to Java and ZabbixJ. I am trying to write a passive ZabbixAgent for a Java application running on 192.168.2.11:10050 and it words fine if I use the ExamplePassiveAgentClient:

Excecuting the command “java ExamplePassiveAgentClient 10050 example.random” returns a random number.

However when I try to connect it to my Zabbix server I get the error message:

“Get value from agent failed: cannot connect to [[192.168.2.11]:10050]: [111] Connection refused”

How can I fix this? My Zabbix server is 5.2

Kind regards 

Allard

**Comment by michaelquigley** [comment]
Sounds like a firewall or network configuration issue. If you're running the `ExamplePassiveAgentClient` on the same host as your agent, it's inside the firewall. Your Zabbix server is trying to connect over the network, presumably and is likely subject to your firewall. You probably need to open port 10050 from your Zabbix server.

**Comment by AllardKrings** [comment]
Hello Michael,

Thaks for your quick reply!

both the zabbix server and the ExampleActiveAgent run on the same linux
machine. ExampleActiveAgent tries to connect to the zabbix server on
127.0.0.1 on port 10051.

The “normal” zabbix agent that runs the zabbix server is turned off.

any suggestions what I am doing wrong?

Kind regards

Allard

p.s. I am trying to build a Zabbix agent in java that runs on z/OS. As far
as I know there is no such thing available at the moment.


Op ma 28 dec. 2020 om 16:46 schreef Michael Quigley <
notifications@github.com>

**Comment by michaelquigley** [comment]
I believe you've got some kind of a network connectivity or firewall problem. Zabbix communicates over a normal TCP socket connection just like SSH or HTTP. I would recommend that you take a look at the firewall on the system running the agent and make sure that your firewall allows the server to connect to that agent on port 10051.
