### ISSUE TITLE
Jar files contain different code than source files

### ISSUE THREAD

**Issue by AllardKrings** [michaelquigley/zabbixj#17]
The ZabbixAgent.java  source code it says:

        public void setServerAddress(String serverAddress) {
		this.serverAddress = serverAddress;
	}

In the ZabbixAgent.class contains the code:

	public void setServerAddress(InetAddress serverAddress) {
		this.serverAddress = serverAddress;

This makes the ExampleActiveAgent causing an error.

**Comment by michaelquigley** [comment]
What's in the repository is a newer version than what's in Maven Central. Either build from source and use that version, or use the version in Maven Central?
